# Cloud Build configuration for AI Music Studio
# Automatically builds and deploys on push to main branch

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-music-studio:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-music-studio:latest'
      - '.'
    timeout: 1200s

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-music-studio:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-music-studio:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-music-studio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-music-studio:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-music-studio:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-music-studio:latest'

# Build timeout
timeout: 1800s

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
